name: Deploy on AWS
on:
  push:
    branches:
      - main
jobs:
  DeployAWS:
    runs_on: self-hosted
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v3
      - name: Make a back-end env file 
        uses: SpicyPizza/create-envfile@v1
        with: 
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          directory: ./back-end
          file_name: .env 
      - name: Make a front-end env file 
        uses: SpicyPizza/create-envfile@v1.3
        with: 
          envkey_REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          directory: ./front-end
          file_name: .env 
      - name: Build project
        run: docker-compose down -v && docker-compose build
      - name: Run project 
        run: docker-compose up -d